### ISSUE TITLE
Améliorer le README.md

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-cote-d-ivoire#8]
Bonjour à tout.te.s !

J'adore utiliser OpenFisca, mais je suis tombé sur un problème que je n'arrive pas à résoudre.

### Voilà ce que j'ai fait:

Je débarque sur le repo

### Voilà ce que je pensais obtenir:

Une description du projet openfisca détaillant la mise en oeuvre pour la Côte d''Ivoire

### Voilà ce que j'ai obtenu:

Une documentation générique peu informative

**Comment by benjello** [comment]
@Leocza : faudrait que l'on décide de ce que l'on laisse sur la page d’accueil pour n'effrayer personne et cependant montrer l'intérêt du projet.

**Comment by Leocza** [comment]
en effet, par défaut le README.md c'est ce que l'on verra sur la page d'accueil ?  
tant qu'on est dans une perspective CEQ, je pense qu'il faut le mentionne quelque part

**Comment by benjello** [comment]
Done
